kits:
  default:
    items:
    - 272 1 knockback:1 fire_aspect:1 durability:3 name:&eTEST
    - 274 1 knockback:1 fire_aspect:1 durability:3
    - book book
    #Syndar
    #kit_nafn
       #items:
       #- item-id fjoldi enchantments nafn
       #- book nafn_a_bók
msg:
  permissions: '&cThu hefur ekki adgang af thessari skipun'
  errorKit: '&cEkki er til neitt svona kit...'
  getKitmessage: '&cThu hefur fengid {kit}!'